import { classListOf, classListsIn, type ClassListSite } from '@/lib/classList'

/**
 * The ink guard, under the decision that a rung owns size and leading
 * while a call site owns weight, tracking and ink.
 *
 * Ink is the third axis of a rung, beside size and weight, and it is named
 * the same way: a surface picks the rung that says what the text IS, not a
 * lightness that says how loud it should look. `text-foreground/70` is a
 * dial. Dialled ink cannot be read back — nobody can say whether /70 and
 * /75 mean two different jobs or two different afternoons — and it does not
 * survive a theme, because the opacity composites against whatever happens
 * to be behind it rather than against a token the theme controls.
 *
 * The named rungs, in order:
 *
 * - `text-foreground` — what the surface is about (titles, values, body)
 * - `text-muted-foreground` — labels, meta, chrome that frames the content
 * - `text-tertiary-foreground` — the quietest step, for text that is
 *   present but not being read (placeholders, disabled, dim counts)
 *
 * A surface that needs an ink none of those name adds a token, which is a
 * decision with a name, rather than a number on a call site.
 *
 * `src/components/ui/**` is exempt: those files are vendored from the CLI
 * and are held pristine by their own guard.
 */

/** An ink utility carrying an opacity suffix, variants and arbitrary values allowed. */
const DIALLED_INK = /(?:^|:)text-[a-z-]*foreground\/(\d{1,3})$/

/** Vendored, regenerated by the component CLI — not ours to re-ink. */
const VENDORED = /^components\/ui\//

/**
 * The named rung a dialled ink should have been written as.
 *
 * The boundaries follow what the conversion actually found in this tree:
 * 80 and above was full-strength text that somebody softened by eye, the
 * seventies and the muted family's own dials were label and meta ink, and
 * anything below sixty was the quiet step.
 *
 * @param level - the opacity suffix, 0-100
 */
export function rungFor(level: number): string {
  if (level >= 80) return 'text-foreground'
  if (level >= 60) return 'text-muted-foreground'
  return 'text-tertiary-foreground'
}

/**
 * Why this class list violates the ink rule, or `null` if it does not.
 *
 * @param site - one class list, as `classLists` / `classListsIn` reports it
 */
export function inkFault(site: ClassListSite): string | null {
  if (VENDORED.test(site.file)) return null
  for (const token of classListOf(site.classes)) {
    const match = token.match(DIALLED_INK)
    if (!match) continue
    const level = Number(match[1])
    return (
      `${token} dials ink: name the rung instead, ` +
      `here ${rungFor(level)}`
    )
  }
  return null
}

/**
 * Every ink fault in `source`.
 *
 * @param source - TypeScript / TSX
 * @param file - path recorded on the reported sites
 */
export function inkFaultsIn(source: string, file = ''): string[] {
  return classListsIn(source, file).flatMap((site) => {
    const fault = inkFault(site)
    return fault ? [`${file}:${site.line}: ${fault}`] : []
  })
}
